### ISSUE TITLE
Plans to update the Podspec repo with the latest version?

### ISSUE THREAD

**Issue by andrewloyola** [segment-integrations/analytics-ios-integration-amplitude#14]
Hi @f2prateek 

We're looking to pick up the latest changes and close #7 , but it looks like the spec repo thinks the latest version is 3.2.0-alpha.  

when using `pod 'Segment-Amplitude'`, a `pod outdated` command reports the following

`Segment-Amplitude 1.2.0 -> 1.2.0 (latest version 3.2.0-alpha)`

can we expect this to be released soon? we'd obviously rather point to the common spec repo than master in this one.

**Comment by f2prateek** [comment]
The latest stable release version is ~~1.2.0~~ 1.4.0. 

For context, when we were first creating this pod I thought it make sense to mimic the version of Amplitude SDK it supports (so 3.2.0 of this library would mean it supported 3.2.0 of Amplitude). We realized this wasn't all that useful since the changes in this library are independent, and ends up creating releases that don't match Amplitude's versioning (e.g. if there was mapping bug in 3.2.0, I would fix it and cut 3.2.1, but it would still be on Amplitude's 3.2.0 version). So we folded the versioning to start from  to 1.0.0 as it made more sense to keep the versioning of the pod independent.

CocoaPods doesn't have a way to delete old pods, so I can't delete the 3.2.0-alpha version.

My understanding was that CocoaPods should only show you stable releases (see https://github.com/CocoaPods/search.cocoapods.org/issues/102 and http://blog.cocoapods.org/Release-Versions-Only/ and https://github.com/CocoaPods/Specs/pull/13644#issuecomment-158203106).I think this is possibly an issue with the pod update command asking you to upgrade to pre-release versions.

**Comment by andrewloyola** [comment]
Understood about the cocoapods versioning overall reasoning.

So just to be clear here about the original question, though there is a 1.4.0 in master, there is no date/estimate you can communicate at this time for when it will be released, if ever?

**Comment by f2prateek** [comment]
Oh my apologies, the latest version released is 1.4.0 (not 1.2.0). It is tagged (https://github.com/segment-integrations/analytics-ios-integration-amplitude/releases/tag/1.4.0), released (https://github.com/segment-integrations/analytics-ios-integration-amplitude/blob/master/CHANGELOG.md#version-140-21st-july-2016) and published (https://github.com/CocoaPods/Specs/blob/master/Specs/Segment-Amplitude/1.4.0/Segment-Amplitude.podspec.json).

There have been no changes in master since the 1.4.0 release. If there were, we will of course continue to make updates to this integration, I was just explaining why you see the rogue 3.2.0-alpha release on CocoaPods.

**Comment by andrewloyola** [comment]
thanks and understood. , appreciate the quick responses!
