### ISSUE TITLE
'FirebaseAnalytics/FirebaseAnalytics.h' file not found

### ISSUE THREAD

**Issue by Sh4rky** [segment-integrations/analytics-ios-integration-amplitude#46]
Even in a new project will fail while compiling.
My current Podfile for a test project is

```ruby
target 'SegmentIntegrationTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Segment-Firebase', '~> 2.0'
  # Pods for SegmentIntegrationTest

end
```

The error shows up in `Firebase.h` with message 'FirebaseAnalytics/FirebaseAnalytics.h' file not found

**Comment by ladanazita** [comment]
@Sh4rky Hi there! Did you mean to open this in the Segment-Firebase repo? 

We have seen this come up before, see [issue here](https://github.com/segment-integrations/analytics-ios-integration-firebase/issues/12). 

The issue comes from Firebase not being served as a dynamic library, so having `use_frameworks!`  included will cause the issue you see.

If you can remove `use_frameworks!` from your podfile, this issue should be resolved. However, if you can't remove that you may need to manually include the integration files in your project. So instead of importing the integration from our library, then you would import the integration from your local copy.

This eliminates the transitive dependency (from App -> Segment-Firebase -> Firebase to App -> Firebase).

**Comment by Sh4rky** [comment]
yes I saw it, but for the lack of response it seemed a little odd that solution and I needed to check.

So should I add manually (aka without using cocoapods) all Segment-Firebase dependencies?

Thanks in advance :)

**Comment by ladanazita** [comment]
Hey @Sh4rky - sorry about the lack of response! Yeah, we have had this issue with [Google Analytics](https://segment.com/docs/destinations/google-analytics/#target-has-transitive-dependencies-that-include-static-binaries) for instance, and added a [subspec workaround](https://github.com/segment-integrations/analytics-ios-integration-google-analytics/blob/master/Segment-GoogleAnalytics.podspec#L38-L45), which would still preserve the files, but you still need to manually add those specific files. 

Until we add this subspec, you will need to natively include the Firebase pod and manually include the [integration files](https://github.com/segment-integrations/analytics-ios-integration-amplitude/tree/master/Pod/Classes).

Let me know if that makes sense!

**Comment by Sh4rky** [comment]
@ladanazita  thanks! I'll try that :)

**Comment by Sh4rky** [comment]
@ladanazita I imported the files you pointed out, I tried with the ones in master and also with the ones in tag 2.0 and 1.0
Then I installed `pod 'Firebase'` and this is what I'm getting

<img width="417" alt="screen shot 2017-10-25 at 6 43 55 pm" src="https://user-images.githubusercontent.com/4087387/32024935-a574aa34-b9b4-11e7-8319-cad5185d8a0b.png">

and it crashes. Only after I try to integrated writing:

```swift
let integration = SEGFirebaseIntegrationFactory.instance()
let configuration = SEGAnalyticsConfiguration(writeKey: self.segmentKey)
configuration.trackApplicationLifecycleEvents = true
configuration.use(integration)
```
