### ISSUE TITLE
Not compatible with official 4.1.0+ Segment SDK release.

### ISSUE THREAD

**Issue by georgenavarro** [segment-integrations/analytics-ios-integration-amplitude#86]
Segment has renamed their module from `Analytics` to `Segment` which is breaking import statements in this project and does not compile. see: https://github.com/segmentio/analytics-ios/releases/tag/4.1.0

**Comment by yawaraym** [comment]
When it is expected to fix?

**Comment by dmitrysimkin** [comment]
Having same build issues.
I saw that #88 was merged to master but not yet released, I tried checkout master locally and use local pod but also had build issues. 
After making changes below locally I was able to build and run my app
![Screen Shot 2020-10-29 at 11 55 11](https://user-images.githubusercontent.com/7154376/97546517-9d275700-19dd-11eb-9ac8-475b63397703.png)
Can you please guys fix it as soon as possible because now I find myself between 2 limitations: from 1 side I'm forced to update to latest segment Analytics version where [this crash](https://github.com/segmentio/analytics-ios/issues/947) fixed, but when I update segment-amplitude integration that I need has build issues. 
Thanks

**UPD**: Also was forced to increase min deployment version to match Segment's (Analytics) to iOS 11.0

**Comment by georgenavarro** [comment]
I am no longer seeing these issues after 3.2.3 release https://github.com/segment-integrations/analytics-ios-integration-amplitude/releases/tag/3.2.3
